name: Deploy

on:
  push:
    branches:
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "vaccine-scheduler-2021-app"
          heroku_email: "csayantan001@gmail.com"
          procfile: "web: npm start"